spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/house_and_tenants
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true
        hbm2ddl.auto: validate

  liquibase:
    changelog: db.changelog/db.changelog-master.yaml
    enabled: true


cache:
  #LRU or LFU
  algorithm: LRU
  capacity: 3
